name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: angularActionsV17/package-lock.json  # 👈 specify the lock file path if needed

      - name: Install dependencies
        run: npm install
        working-directory: angularActionsV17  # 👈 change into your project folder

      - name: Build project
        run: npm run build --if-present
        working-directory: angularActionsV17

      - name: Run tests
        run: npm test
        working-directory: angularActionsV17
